global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'gpu-metrics'
    static_configs:
      - targets: ['cadvisor:8080']
  # - job_name: 'gpu-22'
  #   static_configs:
  #     - targets: ['']
  # - job_name: 'gpu-60'
  #   static_configs:
  #     - targets: ['']
  # - job_name: 'jumper-gpu-22'
  #   static_configs:
  #     - targets: ['']
  # - job_name: 'jumper-gpu-60'
  #   static_configs:
  #     - targets: ['']
  # - job_name: 'dheyo01'
  #   static_configs:
  #     - targets: ['']



